### ISSUE TITLE
when removing wikilinks, don't ever delete, even from lists

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/xfdcloser#95]
Requested by Paper9oll at https://en.wikipedia.org/wiki/Wikipedia_talk:XFDcloser#Bug%3F

Currently, XFDcloser sometimes uses the edit summary of "Removing link(s) / list item(s)" when removing wikilinks from deleted pages. [Example.](https://en.wikipedia.org/w/index.php?diff=1263910465) This suggests that it is intentionally programmed to sometimes "remove list items", in other words delete list items, when removing wikilinks.

It'd be safer not to ever delete. Only de-wikilink.

**Comment by primefac** [comment]
Disagree with the need for this; https://en.wikipedia.org/wiki/Wikipedia:XFDcloser#Unlinking_backlinks indicates that both options are possible, and doing something wrong thus falls to the editor who pressed the buttons.

In other words, we should not hamstring the script because people sometimes misclick. Editors are responsible for their edits with tools and scripts.
